apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: $APP_INSTANCE_NAME-prometheus-config
  labels:
    app.kubernetes.io/name: $APP_INSTANCE_NAME
    app.kubernetes.io/component: prometheus
data:
  prometheus.yml: |
  global:
    scrape_interval: 30s
  
  scrape_configs:
    - job_name: 'prometheus'
      static_configs:
      - targets: ['localhost:9090']

    - job_name: 'kubernetes-nodes'
      kubernetes_sd_configs:
      - role: node
      relabel_configs:
      - source_labels: [10.10.11.15]
        regex: (.+):(.+)
        target_label: 10.10.11.15
        replacement: ${1}:9101
