apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: $APP_INSTANCE_NAME-prometheus
  labels: &Labels
    k8s-app: prometheus
    app.kubernetes.io/name: $APP_INSTANCE_NAME
    app.kubernetes.io/component: prometheus
spec:
  serviceName: "$APP_INSTANCE_NAME-prometheus"
  replicas: 1
  podManagementPolicy: "Parallel"
  updateStrategy:
    type: "RollingUpdate"
  selector:
    matchLabels: *Labels
  template:
    metadata:
      labels: *Labels
    spec:
      serviceAccountName: prometheus
      initContainers:
      - name: "init-chown-data"
        image: debian:9
        imagePullPolicy: Always
        command: ["chmod", "-R", "777", "/prometheus"]
        volumeMounts:
        - name: $APP_INSTANCE_NAME-prometheus-data
          mountPath: /prometheus
          subPath: ""
      containers:
        - name: prometheus-server
          image: prom/prometheus:v2.19.2
          imagePullPolicy: "IfNotPresent"
          args:
            - --config.file=/etc/config/prometheus.yaml
            - --storage.tsdb.path=/data
            - --web.console.libraries=/etc/prometheus/console_libraries
            - --web.console.templates=/etc/prometheus/consoles
            - --web.enable-lifecycle
          ports:
            - containerPort: 9090
            readinessProbe:
            httpGet:
              path: /-/ready
              port: 9090
            initialDelaySeconds: 30
            timeoutSeconds: 30
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9090
            initialDelaySeconds: 30
            timeoutSeconds: 30
          resources:
            requests:
              cpu: 200m
              memory: 1000Mi
          volumeMounts:
            - name: config-volume
              mountPath: /prometheus
            - name: $APP_INSTANCE_NAME-prometheus-data
              mountPath: /prometheus
              subPath: ""
      terminationGracePeriodSeconds: 300
      volumes:
          - name: config-volume
          configMap:
            name: $APP_INSTANCE_NAME-prometheus-config
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: k8s-app
                operator: In
                values:
                - prometheus
            topologyKey: "kubernetes.io/hostname"
`/data/`
  volumeClaimTemplates:
  - metadata:
      name: $APP_INSTANCE_NAME-prometheus-data
      labels: *Labels
    spec:
      storageClassName: do-block-storage
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: "5Gi"
