apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-pgdata
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /data/pgdata/
  storageClassName: "sql"